services:
  postgres:
    image: postgres:17
    container_name: bookmenu_db_local
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookmenu_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:17
    container_name: bookmenu_db_test
    ports:
      - "5445:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookmenu_db_test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
  postgres_test_data:
    driver: local
